### ISSUE TITLE
Set up docs on s3

### ISSUE THREAD

**Issue by kgardnr** [coralproject/install#14]
- [x] Eugene create IAM user for David Jay
- [x] David Jay to set up lambda script
- [x] David Jay to create s3 bucket 
- [x] Setup Cloudfront
- [ ] Talk to Ann about how she's deploying and figure out how we want to handle it
- [x] Eugene to handle CNAME #
- [x] David Jay to add SSL cert to cloudfront

**Comment by davidgljay** [comment]
Setting up lambda function this way:

https://aws.amazon.com/blogs/compute/dynamic-github-actions-with-aws-lambda/

It might be good to do this on Iron.io, but that s3 access will be a little more straightforward this way.

**Comment by davidgljay** [comment]
I've created a script which syncs between github and S3 and created an iron worker which executes it every time github is updated.

Quick question @kgardnr: Do we want to copy the entire repo over, or just the /site directory?

**Comment by davidgljay** [comment]
Ok, the new SSL certificate is approved and propagating on CloudFront, https://docs.cloudfront.net should be up in a few minutes.

I'm adding a PR with the scripts used to copy the docs over. Here's the process as it stands:

1) A commit is made to master in coralproject/docs
2) An iron.io worker is booted up that downloads the repo and copies it to S3 
   (This takes about a minute because of some slower-than-expected docker issues. I can optimize it but it doesn't seem like it matters.)
   (This worker runs in a custom docker container, coralproject/docsync, which I've added to Docker Hub.)
3) S3 propogates it to CloudFront, which makes the data available globally with low latency. 
   (This takes 2-3 minutes.)

**Comment by davidgljay** [comment]
Here is a PR with the script used to accomplish this task: 

https://github.com/coralproject/docs/pull/52
